# fly.toml app configuration file generated for phonebook-icy-field-1927 on 2025-02-28T16:11:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-icy-field-1927'
primary_region = 'sin'

[build]
[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
