@baseUrl = http://localhost:3001

get {{baseUrl}}/api/users

###
get {{baseUrl}}/api/blogs

###
post {{baseUrl}}/api/users
Content-Type: application/json

{
   "username": "andy",
   "name": "andy",
  "password": "andworm"
}

###
post {{baseUrl}}/api/login
Content-Type: application/json

{
  "username": "andy",
  "password": "andworm"
}

###
post {{baseUrl}}/api/blogs
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZHkiLCJpZCI6IjY3ZTY1Yjk3ZmZhZTFiMjU4MGYxZGUzZSIsImlhdCI6MTc0MzE1NDUwMX0.PVpAf6xcD9dvDHFg6TWcnEJCJGvLqqf2qJxeuu16oHw

{
  "title": "Bible",
  "author": "John Ormsby",
  "url": "https://deafening-story.org",
  "likes": 76
}


